### ISSUE TITLE
Version of trimesh & SMARTS

### ISSUE THREAD

**Issue by BravoFr0st** [zbzhu99/NGSIM_SMARTS#4]
For the latest version of SMARTS (0.4.18, on 2021/12/4) , trimesh version below 3.9.29 is not available.

And after updating trimesh from 3.9.20 to 3.9.29,  
`TypeError: export_glb() got an unexpected keyword argument 'extras'` does not appear again.

**Comment by zbzhu99** [comment]
Thank you for pointing out this! I will update the README file.
